name: MSBuildForUnity NuGet Build

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  build-nuget-solution:
    name: "Build NuGet Solution"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Build
      run: dotnet build -c Debug Source/MSBuildTools.Unity.Nuget/MSBuildForUnity.NuGet.sln
    - name: Stage Artifacts
      shell: pwsh
      run: |
        $targetFolder = [System.IO.Path]::Combine("$env:GITHUB_WORKSPACE","Artifacts")
        $binFolders = Get-ChildItem -Directory -Filter bin -Recurse
        foreach ($binFolder in $binFolders)
        {
            Copy-Item $binFolder.FullName -Recurse -Destination ([System.IO.Path]::Combine("$targetFolder", "$(Resolve-Path -Relative $binFolder.FullName)"))
        }
    - uses: actions/upload-artifact@v1
      with:
        name: Artifacts
        path: Artifacts
        